version: "3"

services:
  redis:
    build:
      context: ./redis
    networks:
      - back-end

  db:
    build:
      context: ./postgres
    networks:
      - back-end
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - postgres.env

  vote:
    build:
      context: ./vote
    networks:
      - back-end
      - front-end

  result:
    build:
      context: ./result
    networks:
      - back-end
      - front-end

  worker:
    build:
      context: ./worker
    networks:
      - back-end

networks:
  back-end:
    driver: bridge
  front-end:
    driver: bridge

volumes:
  postgres-data:
